import tkinter as tk
from tkinter import filedialog, messagebox, ttk
from pathlib import Path
import threading

from tkinterdnd2 import DND_FILES, TkinterDnD

from src.pose_processor import process_video, SUPPORTED_EXTENSIONS
from src.id_selection_window import IDSelectionWindow


BASE_DIR = Path(__file__).resolve().parent

VIDEOS_DIR = BASE_DIR / "videos"
RESULTS_DIR = BASE_DIR / "results"
MODEL_PATH = BASE_DIR / "models" / "yolo26x-pose.pt"

VIDEOS_DIR.mkdir(exist_ok=True)
RESULTS_DIR.mkdir(exist_ok=True)

def find_output_video(folder):
    """
    Find the video generated by YOLO inside the result folder.
    """

    video_extensions = (
        ".mp4",
        ".avi",
        ".mov",
        ".mkv"
    )

    videos = [
        f for f in folder.iterdir()
        if f.is_file() and f.suffix.lower() in video_extensions
    ]

    if not videos:
        return None

    # Prefer a file having the same name as the original video
    return videos[0]

class PoseApp(TkinterDnD.Tk):

    def __init__(self):

        super().__init__()

        self.title("Analyse de mouvements")
        self.geometry("700x500")
        self.minsize(600, 450)

        self.video_path = None
        self.processing = False

        self.create_widgets()

    def create_widgets(self):
        """
        Crée les widgets de l'interface graphique.
        """

        title = tk.Label(
            self,
            text="Analyse de mouvements du nourrisson",
            font=("Arial", 20, "bold")
        )

        title.pack(pady=(25, 5))

        subtitle = tk.Label(
            self,
            text="Sélectionnez une vidéo pour lancer l'analyse.",
            font=("Arial", 11)
        )

        subtitle.pack(pady=(0, 20))

        self.drop_zone = tk.Label(
            self,
            text="Glissez-déposez une vidéo ici",
            relief="solid",
            borderwidth=2,
            height=5,
            font=("Arial", 13)
        )

        self.drop_zone.pack(
            fill="x",
            padx=50,
            pady=10
        )

        self.drop_zone.drop_target_register(DND_FILES)

        self.drop_zone.dnd_bind(
            "<<Drop>>",
            self.on_drop
        )

        self.select_button = tk.Button(
            self,
            text="Sélectionner une vidéo",
            command=self.select_video,
            width=25,
            height=2
        )

        self.select_button.pack(pady=10)

        self.video_label = tk.Label(
            self,
            text="Aucune vidéo sélectionnée",
            font=("Arial", 10)
        )

        self.video_label.pack(pady=10)

        self.progress = ttk.Progressbar(
            self,
            orient="horizontal",
            mode="determinate",
            length=500
        )

        self.progress.pack(pady=(20, 5))

        self.progress_label = tk.Label(
            self,
            text="En attente",
            font=("Arial", 10)
        )

        self.progress_label.pack()

        self.start_button = tk.Button(
            self,
            text="Lancer l'analyse",
            command=self.start_processing,
            width=25,
            height=2,
            state="disabled"
        )

        self.start_button.pack(pady=20)

        self.status_label = tk.Label(
            self,
            text="",
            font=("Arial", 10)
        )

        self.status_label.pack(pady=5)

    def is_valid_video(self, path):

        return (
            Path(path).suffix.lower()
            in SUPPORTED_EXTENSIONS
        )

    def set_video(self, path):

        path = Path(path)

        if not self.is_valid_video(path):

            messagebox.showerror(
                "Format non supporté",
                (
                    "Veuillez sélectionner une vidéo "
                    "(.mp4, .avi, .mov ou .mkv)."
                )
            )

            return

        self.video_path = path
        self.video_label.config(text=f"Vidéo sélectionnée : {path.name}")
        self.start_button.config(state="normal")
        self.status_label.config(text="Vidéo prête à être analysée.")

    def on_drop(self, event):

        paths = self.tk.splitlist(event.data)

        if paths:
            self.set_video(paths[0])

    def select_video(self):

        path = filedialog.askopenfilename(
            title="Sélectionner une vidéo",
            initialdir=VIDEOS_DIR,
            filetypes=[
                (
                    "Vidéos",
                    "*.mp4 *.avi *.mov *.mkv"
                ),
                (
                    "Tous les fichiers",
                    "*.*"
                )
            ]
        )

        if path:
            self.set_video(path)

    def start_processing(self):

        if self.video_path is None:
            return

        if self.processing:
            return

        if not MODEL_PATH.exists():

            messagebox.showerror(
                "Modèle introuvable",
                (
                    "Le modèle YOLO est introuvable :\n\n"
                    f"{MODEL_PATH}"
                )
            )

            return

        self.processing = True

        self.select_button.config(state="disabled")
        self.start_button.config(state="disabled")
        self.progress["value"] = 0
        self.progress_label.config(text="0 %")
        self.status_label.config(text="Analyse YOLO en cours...")

        thread = threading.Thread(
            target=self.run_processing,
            daemon=True
        )

        thread.start()

    def update_progress(self, value):

        self.after(
            0,
            lambda: self._update_progress(value)
        )

    def _update_progress(self, value):

        self.progress["value"] = value

        self.progress_label.config(
            text=f"{value:.0f} %"
        )

    def run_processing(self):
        """
        Exécute le traitement de la vidéo.
        """
        
        try:
            all_csv = process_video(
                self.video_path,
                results_dir=RESULTS_DIR,
                model_path=MODEL_PATH,
                progress_callback=self.update_progress
            )

            self.after(
                0,
                lambda: self.processing_finished(
                    all_csv
                )
            )
        except Exception as error:

            self.after(
                0,
                lambda: self.processing_failed(
                    error
                )
            )

    def processing_finished(self, all_csv):
        """
        Affiche la fenêtre de sélection des IDs après la fin du traitement.
        """

        self.processing = False

        self.select_button.config(state="normal")
        self.progress["value"] = 100
        self.progress_label.config(text="100 %")
        self.status_label.config(text="Analyse YOLO terminée.")

        output_dir = RESULTS_DIR / self.video_path.stem

        annotated_video = find_output_video(output_dir)

        if annotated_video is None:

            self.start_button.config(state="normal")
            messagebox.showerror(
                "Vidéo introuvable",
                (
                    "L'analyse YOLO est terminée, "
                    "mais la vidéo annotée n'a pas été trouvée."
                )
            )
            return

        # Ouvre la fenêtre de sélection des IDs
        self.status_label.config(text="Sélectionnez maintenant les IDs du bébé.")

        IDSelectionWindow(
            self,
            annotated_video,
            all_csv,
            output_dir
        )

    def processing_failed(self, error):
        """
        Affiche un message d'erreur si le traitement échoue.
        """

        self.processing = False

        self.select_button.config(state="normal")
        self.start_button.config(state="normal")
        self.status_label.config(text="Une erreur est survenue.")

        messagebox.showerror(
            "Erreur",
            (
                "L'analyse n'a pas pu être terminée.\n\n"
                f"{error}"
            )
        )

if __name__ == "__main__":

    app = PoseApp()
    app.mainloop()